<?php

return [
    
    /*
    |--------------------------------------------------------------------------
    | Global Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the global website.
    |
    */
	
	'Jobs ads in the World' => 'Quảng cáo việc làm trên thế giới',
    'Jobs ads in :location' => 'Quảng cáo việc làm tại: vị trí',
	'Find a job near you' => 'Tìm một công việc gần bạn',
	'Simple, fast and efficient' => 'Đơn giản, nhanh chóng và hiệu quả',
    'Looking for a job' => 'Tìm việc làm',
    'Post your Job ads here' => 'Đăng quảng cáo việc làm của bạn ở đây',
    'Free Ads' => 'Quảng cáo miễn phí',
    'Jobs' => 'Việc làm',
    'Jobs in' => 'Jobs in',
    'Jobs in :location' => 'Việc làm ở :location',
    'Jobs in :category' => 'Việc làm trong :category',
    'Jobs :category in :location' => 'Việc làm :category ở :location',
    'Search for' => 'Tìm kiếm',
    'jobs' => 'Việc làm',
    'jobs in' => 'jobs in',
    'Latest jobs' => 'Công việc mới nhất',
    ':count job ads' => ':count' . 'Quảng cáo việc làm',
    ':count job ads in :location' => ':count' . 'Quảng cáo ở <strong>:location</strong>',
    '100% Job ads' => '100% Quảng cáo việc làm',
    'Jobs in the World' => 'Việc làm trên thế giới',
    'Select a country' => 'Chọn một quốc gia',
    'Select your country to start' => 'Chọn quốc gia của bạn để bắt đầu',
    'I\'m looking for a ...' => ' Tôi đang tìm kiếm một ...',
    'Location (City) ...' => 'Vị trí (Thành phố) ...',
    'What?' => 'Cái gì ?',
    'Where?' => 'Ở đâu ?',
    'Select your Location' => 'Chọn vị trí của bạn',
    'Please select your location before' => 'Vui lòng chọn vị trí của bạn trước',
    'Find' => 'Tìm thấy',
    'Search' => 'Tìm kiếm',
	'Looking for a job?' => 'Tìm 1 công việc?',
	'Upload your Resume and easily apply to jobs from any device!' => 'Tải lên Hồ sơ của bạn và dễ dàng áp dụng cho công việc từ bất kỳ thiết bị nào!',
	'Upload your Resume' => 'Tiếp tục tải lên',
    'Post a Job' => 'Đăng việc làm',
    'Create a Job ad' => 'Đăng việc làm',
    'Post your Job' => 'Đăng việc làm',
    'Start Now!' => 'Bắt đầu ngay bây giờ',
    'e.g. PHP Developer' => 'e.g. PHP Developer',
    'All Categories' => 'Tất cả danh mục',
    'Others Categories' => 'Tất cả danh mục',
    'Salary range' => 'Mức lương',
    'Condition' => 'Điều kiện',
    'New' => 'Mới',
    'Used' => 'Đã sử dụng',
    'None' => 'None',
    'Location' => 'vị trí',
    'Locations' => 'nhiều vị trí',
    'Urgent' => 'gấp',
    'Urgent Jobs only' => 'Chỉ việc làm cần gấp',
    ':app_name is also available in your country: :country. Starting good opportunities here now!' => ':app_name có sẵn ở quốc gia của bạn: <a href=":url"><strong>:quốc gia</strong></a>. Bắt đầu cơ hội tốt <a href=":url"><strong>đây</strong></a> ngay bây giờ!',
    'Login for faster access to the best deals. Click here if you don\'t have an account.' => '<a href=":login_url"><strong>Đăng nhập</strong></a> để truy cập nhanh hơn vào các giao dịch tốt nhất. <a href=":register_url"><strong>Click here</strong></a> Nếu bạn không có tài khoản.',
    'List of Categories and Sub-categories' => 'Danh sách các danh mục và danh mục phụ',
    'List of Cities in' => 'Danh sách các thành phố',
	
    'Home' => 'Trang chủ',
    'About us' => 'Về chúng tôi',
    'FAQ' => 'FAQ',
    'Sitemap' => 'Sơ đồ trang web',
    'Countries' => 'Quốc gia',
    'Terms' => 'Ddieuf kiện',
    'Privacy' => 'Riêng tư',
    'All Rights Reserved' => 'All Rights Reserved',
    
    
    // Login
    'Password' => 'Mật khẩu',
    'Submit' => 'Gửi',
    'Keep me logged in' => 'Ghi nhớ đăng nhập',
    'Lost your password?' => 'Quên mật khẩu?',
    'Don\'t have an account?' => 'Chưa có tài khoản?',
    'Signup' => 'Signup',
    'Sign Up' => 'Đăng ký',
	'Signin' => 'Signin',
	'Sign In' => 'Đăng nhập',
	'Login' => 'Login',
	'Log In' => 'Đăng nhập',
	'Logout' => 'Logout',
	'Log Out' => 'Đăng xuất',
	'Signout' => 'Signout',
	'Sign Out' => 'Đăng xuất',
    
    // Signup
    'Create your account, Its free' => 'Tạo tài khoản của bạn, Miễn phí 100%',
    'Gender' => 'Giới tính',
    'Select a gender' => 'Chọn giới tính',
    'Male' => 'Nam',
    'Female' => 'Nữ',
    'Mr' => 'Mr',
    'Mrs' => 'Mrs',
    'First Name' => 'Tên',
    'Last Name' => 'Họ',
    'You are a' => 'Bạn là một',
	'Employers' => 'Nhà tuyển dụng',
	'Job seekers' => 'Người tìm việc',
	'Employer' => 'Employer',
	'Job seeker' => 'Job seeker',
	'Company' => 'Công ty',
    'Company name' => 'Tên công ty',
    'Company Name' => 'Company Name',
	'Company Description' => 'Mô tả về công ty',
    'Your Country' => 'Công ty của bạn',
    'Country' => 'Quốc giá',
    'Phone' => 'Điện thoại',
    'Phone Number' => 'Số điện thoại',
    'Email' => 'Email',
    'Please repeat your password' => 'Lặp lại mật khẩu',
    'At least 5 characters' => 'Ít nhất 5 ký tự',
    'I have read and agree to the <a :attributes>Terms & Conditions</a>' => 'tôi đã đọc và đồng ý với <a :attributes>Điều khoản và điều kiện</a>',
    'By continuing on this website, you accept our <a :attributes>Terms of Use</a>' => 'Bằng cách tiếp tục trên trang web này, bạn chấp nhận <a :attributes>Điều khoản sử dụng</a>',
    'By continuing on this website, you accept our <a :attributes>Terms of Use</a> and Posting Rules' => 'Bằng cách tiếp tục trên trang web này, bạn chấp nhận <a :attributes>Điều khoản sử dụng</a> và quy tắc đăng bài',
    'Register' => 'Đăng ký',
    
    'Your message has been sent to our moderators' => 'Thông tin của bạn đã được gửi đến nhà điều hành.',
    'Your message has been sent to our moderators. Thank you' => 'Thông tin của bạn đã được gửi đến nhà điều hành. Cám ơn bạn.',
    
    'Post a Job' => 'Đăng một công việc',
    'Post a Job' => 'Post a Job',
    'Create and Manage Jobs' => 'Tạo và quản lý việc làm',
    'Become a best company. Create and Manage your jobs. Repost your old jobs, etc.' => 'Trở thành một công ty tốt nhất. Tạo và Quản lý việc làm của bạn. Thay thế lại việc làm cũ của bạn, v.v ...',
    'Create your Favorite jobs list.' => 'Tạo danh sách việc làm yêu thích của bạn.',
    'Create your Favorite jobs list, and save your searchs. Don\'t forget any opportunity!' => 'Tạo danh sách công việc ưa thích của bạn. Và lưu tìm kiếm của bạn. Đừng bỏ lỡ bất cứ cơ hội nào.',
	'Do you have a post to be filled within your company? Find the right candidate in a few clicks at :app_name' => 'Bạn có một bài viết để được điền vào trong công ty của bạn? Tìm đúng ứng cử viên trong một vài cú nhấp chuột tại :app_name.',
    
    // Post Ads
    'Post a Job' => 'Đăng công việc',
    'Category' => 'Danh mục',
    'Select a category' => 'Chọn  mottj danh mục',
    'Sub-Category' => 'Danh mục phụ',
    'Select a sub-category' => 'Chọn một danh mục phụ',
    'Job Type' => 'Loại công việc',
    'Type' => 'Loại',
    'Title' => 'Tiêu đề',
    'Job Title' => 'Tiêu đề của việc làm',
	'Job\'s Title' => 'Tiêu đề nhiều việc làm',
    'A great title needs at least 60 characters.' => 'Tiêu đề lớn cần ít nhất 60 ký tự.',
    'Describe ad' => 'Mô tả quảng cáo',
	'Describe the company' => 'Mô tả công ty',
    'Describe what makes your ad unique' => 'Mô tả làm cho quảng cáo của bạn trở nên độc đáo',
    'Salary' => 'Lương',
	'Salary (min)' => 'Lương (thấp nhất)',
	'Salary (max)' => 'Lương (Lớn nhất)',
    'e.i. 15000' => 'ví dụ 15000',
    'Negotiable' => 'Thương lượng',
    'Logo' => 'Logo',
    'Your resume' => 'Hồ sơ của bạn',
    'Resume format' => 'Format : pdf, doc, docx, odt, rtf, jpg, png',
	'Logo format' => 'Format : jpg, jpeg, png, gif',
    'File types: :file_types' => 'Loại tập tin: :file_types',
    'Browse' => 'Browse',
    'Add up to :pictures_number photos. Use a real image of your product, not catalogs.' => 'Thêm vào :pictures_number ảnh. Sử dụng hình ảnh thực của sản phẩm của bạn chứ không phải danh mục sản phẩm.',
	'Company Information' => 'Thông tin công ty',
    'Company information' => 'Company information',
	'Company Website' => 'Trang web của công ty',
	'Website' => 'Website',
	'Web' => 'Web',
    'Contact Name' => 'Tên liên lạc',
    'Contact Email' => 'Email liên lạc',
    'Phone Number (in local format)' => 'Số điện thoại (bố cục định dạng)',
    'Hide the phone number on this ads.' => 'Ẩn số điện thoại trên quảng cáo này.',
    'Location' => 'Vị trí',
    'Select a location' => 'Chọn 1 vị trí',
    'Sub-location' => 'vị trí phụ',
    'Select a sub-location' => 'Chọn 1 vị trí phụ',
    'City' => 'Thành phố',
    'Select a city' => 'Chọn 2 thành phố',
    'Cities' => 'Các thành phố',
	'Start Date' => 'Ngày bắt đầu',
    
    'How to find quickly a candidate?' => 'Làm thế nào để tìm một ứng cử viên một cách nhanh chóng?',
    'Use a brief title and description of the ad' => 'Sử dụng tiêu đề và mô tả ngắn gọn của quảng cáo',
    'Make sure you post in the correct category' => 'Đảm bảo rằng bạn đăng trong đúng danh mục',
    'Add nice photos to your ad' => 'Thêm ảnh đẹp vào quảng cáo của bạn',
    'Add a logo to your ad' => 'Thêm một logo vào quảng cáo của bạn',
    'Put a min and max salary' => 'Đặt mức lương tối thiểu và tối đa',
    'Check the ad before publish' => 'Kiểm tra lại quảng cáo trước khi đăng',
    
    
    'My ads' => 'Việc làm của tôi',
    'My ads on :app_name' => 'Việc làm của tôi trên :app_name',
    'The repost has failed. Please try again.' => 'Báo cáo thất bại. xin vui lòng thử lại.',
    'The repost has done successfully.' => 'Báo cáo thành công.',
    'My archived ads' => 'Việc làm của tôi đã lưu trữ',
    'My archived ads on :app_name' => 'Việc làm của tôi đã lưu trữ :app_name',
    'My favourite jobs' => 'Công việc yêu thích của tôi',
    'My favourite jobs on :app_name' => 'Công việc yêu thích của tôi trên :app_name',
    'My pending approval ads' => 'Việc làm của tôi đã được phê duyệt',
    'My pending approval ads on :app_name' => 'Việc làm của tôi đã được phê duyệt :app_name',
    'My saved search' => 'Tìm kiếm đã lưu',
    'My saved search on :app_name' => 'Tìm kiếm đã lưu trên :app_name',
    'No deletion is done. Please try again.' => 'Xóa thất bại. xin vui lòng thử lại.',
    'Your account details has updated successfully.' => 'Chi tiết tài khoản của bạn đã được cập nhật thành công.',
    
    'Your details account has updated successfully.' => 'Tài khoản chi tiết của bạn đã được cập nhật thành công.',
    'Your settings account has updated successfully.' => 'Cài đặt tài khoản  của bạn đã được cập nhật thành công.',
    
    'My account' => 'Tài khoản của tôi',
    'My account on :app_name' => 'Tài khoản của tôi :app_name',

	'Your message has sent successfully' => 'Tin nhắn của bạn đã gửi thành công',
    'Your message has sent successfully to :contact_name.' => 'Tin nhắn của bạn đã gửi thành công đến :contact_name.',
    'Your report has sent successfully to us. Thank you!' => 'Báo cáo của bạn đã gửi thành công cho chúng tôi. Cám ơn bạn!',
    
    'Posting Ads was disabled for this time. Please try later. Thank you.' => 'Đăng việc làm đã bị vô hiệu trong thời gian này. Hãy thử lại sau. Cảm ơn bạn.',
    'Your ad has been created.' => 'Quảng cáo của bạn đã được tạo.',
    
    'Update My Ad' => 'Cập nhật Quảng cáo của Tôi',
    'Your ad has been updated.' => 'Quảng cáo của bạn đã được cập nhật.',
    
    'Log in' => 'Đăng nhập',
    'Log in to :app_name' => 'Đăng nhập đến :app_name',
    'The Email Address or Password don\'t match.' => 'Địa chỉ Email hoặc Mật khẩu không khớp.',
    'You have been logged out.' => 'Bạn đã được đăng xuất.',
    
    'Sign Up on :app_name !' => 'Đăng ký vào :app_name !',
    'Your account has been created.' => 'Tài khoản của bạn đã được tạo.',
    
    'Welcome to :app_name' => 'Chào mừng đến với :app_name !',
    'Welcome to :app_name : 100% Free Job Board' => 'Chào mừng đến với :app_name : miễn phí 100%. Tìm một công việc gần bạn. Đơn giản, nhanh chóng và hiệu quả.',
    
    'My Ads' => 'Công việc của tôi',
    'Archived ads' => 'Lưu trữ việc làm',
    'Favourite jobs' => 'Việc làm ưa thích',
    'Pending approval' => 'Chờ phê duyệt',
    'Posts' => 'Đăng',
    'Ads' => 'Việc làm',
    'Select' => 'Chọn',
    'All' => 'Tất cả',
    'Delete' => 'Xóa',
    'clear' => 'dọn dẹp',
    'Ads Details' => 'Chi tiết việc làm',
    'Posted On' => 'Đăng trên',
    'Visitors' => 'Khách',
    'Located In' => 'Nằm ở',
    'Edit' => 'Sửa',
    'Share' => 'Chia sẻ',
    'Repost' => 'Báo cáo',
    
    'Close account' => 'Đóng tài khoản',
    'You are sure you want to close your account?' => 'Bạn chắc chắn muốn đóng tài khoản của mình?',
    'Yes' => 'Yes',
    'No' => 'No',

    'count_posts' => '{0} job|{1} job|[2,*] jobs',
    'count_visits' => '{0} visit|{1} visit|[2,*] visits',
    'count_favorites' => '{0} Favorite|{1} Favorite|[2,*] Favorites',
    'count_views' => '{0} view|{1} view|[2,*] views',
    
    'Oops ! An error has occurred. Please correct the red fields in the form' => 'Rất tiếc! Một lỗi đã xảy ra. Vui lòng sửa các trường màu đỏ trong biểu mẫu',
    'visits' => 'visits',
    'Favorites' => 'Favorites',
    'Hello' => 'Hello',
    'You last logged in at' => 'Lần cuối bạn đăng nhập tại',
    'My details' => 'My details',
    'Hide the phone number on the published ads.' => 'Ẩn số điện thoại trên các quảng cáo đã xuất bản.',
    'About Yourself' => 'Về bản thân bạn',
    'Update' => 'Cập nhập',
    'Settings' => 'Cài đặt',
    'Comments are enabled on my ads' => 'Nhận xét được bật trên quảng cáo của tôi',
    'Disable comments on my ads' => 'Vô hiệu hoá nhận xét trên quảng cáo của tôi',
    'New Password' => 'Mật khẩu mới',
    'Confirm Password' => 'Nhập lại mật khẩu',
    'Preferences' => 'Sở thích',
    'I want to receive newsletter.' => 'Tôi muốn nhận bản tin.',
    'I want to receive advice on buying and selling.' => 'Tôi muốn nhận được lời khuyên về mua bán.',
    
    'Saved search' => 'Lưu tìm kiếm',
	'Saved searches' => 'Đã lưu tìm kiếm',
    'You have no saved search.' => 'Bạn không có tìm kiếm đã lưu.',
    'Business Ads' => 'Quảng cáo doanh nghiệp',
    'Private Ads' => 'Quảng cáo Riêng',
    'B' => 'B',
    'P' => 'P',
    'Please select a saved search to show the result' => 'Vui lòng chọn một tìm kiếm đã lưu để hiển thị kết quả',
    'No result. Refine your search using other criteria.' => 'Không có kết quả. Tinh chỉnh tìm kiếm của bạn bằng các tiêu chí khác.',
    
    'Close' => 'đóng',
    'There\'s something wrong with this ads?' => 'Đã xảy ra lỗi với quảng cáo này?',
    'Reason' => 'Lý do',
    'Select a reason' => 'Chọn lý do',
    'Your E-mail' => 'E-mail của bạn',
    'Message' => 'tin nhắn',
    'Cancel' => 'Hủy bỏ',
    'Send Report' => 'Gửi báo cáo',
    
    'Warning! This ad has expired. The product or service is not more available (may be)' => '<strong>Cảnh báo !</strong> Quảng cáo này đã hết hạn. Sản phẩm hoặc dịch vụ không có sẵn (may be)',
    'Back to Results' => 'Quay lại kết quả',
    ':type Job' => ':type việc làm',
    'Job Details' => 'Chi tiết công việc',
    'Salary' => 'Lương',
    'Item' => 'Item',
    'More jobs by this Company' => 'Thêm công việc của công ty này',
	'More jobs by this User' => 'Thêm công việc của người dùng này',
	'More jobs by :company' => 'Thêm công việc bởi :company',
	'More jobs by :user' => 'Thêm công việc bởi :user',
    'Remove favorite' => 'Xóa mục ưa thích',
    'Save ad' => 'Lưu quảng cáo',
    'Share ad' => 'Chia sẻ quảng cáo',
    'Report abuse' => 'Báo cáo lạm dụng',
    'My Resume' => 'Lý lịch của tôi',
    'Resume' => 'Tiếp tục',
    'Download the resume' => 'Tải bản lý lịch',
    'Apply Online' => 'Đăng ký trực tuyến',
    'Contact Company' => 'Liên hệ Công ty',
    'Tips for candidates' => 'Mẹo dành cho ứng viên',
    'Check if the offer matches your profile' => 'Kiểm tra xem phiếu mua hàng có phù hợp với hồ sơ của bạn hay không',
    'Check the start date' => 'Kiểm tra ngày bắt đầu',
    'Meet the employer in a professional location' => 'Gặp gỡ nhà tuyển dụng ở vị trí chuyên nghiệp',
    'Know more' => 'Biết nhiêu hơn',
    'View phone' => 'Xem điện thoại',

    'Contact Employer' => 'Liên hệ với Nhà tuyển dụng',
    'Contact advertiser' => 'Liên hệ với nhà quảng cáo',
    'Name' => 'Tên',
    'Your name' => 'Tên của bạn',
    'E-mail' => 'E-mail',
    'i.e. you@gmail.com' => 'ví dụ you@gmail.com',
    'Your message here...' => 'Tin nhắn của bạn ở đây...',
    'Send message' => 'Gửi tin nhắn',
    
    'Congratulations!' => 'Xin chúc mừng!',
    'Oops!' => 'Rất tiếc!',
    
    'Download current Resume' => 'Tải về hồ sơ hiện tại',
    
    'Email Address' => 'Địa chỉ Email',
    'Send Password Reset Link' => 'Gửi Liên kết Đặt lại Mật khẩu',
    'Back to the Log In page' => 'Quay lại trang đăng nhập',
    'Sign Up !' => 'Đăng ký !',
    
    'Reset your Password' => 'Đặt lại mật khẩu của bạn',
    'Reset Password' => 'Đặt lại mật khẩu',
    'Password Confirmation' => 'Xác nhận mật khẩu',
    'Reset the Password' => 'Đặt lại mật khẩu',
    
    ':domain, a Jobs Portal website. Simple, fast and efficient.' => ':domain, Trang web cổng thông tin việc làm. Đơn giản, nhanh chóng và hiệu quả.',
    
    'Choose a city' => 'Chọn một thành phố',
    'More cities' => 'Thêm thành phố',
    
    'Phishing' => 'Lừa đảo',
    
    'Personal Home' => 'Trang cá nhâne',
    'Payment history' => 'Lịch sử thanh toán',
    
    'Top Ads' => 'Top',
    'Featured Ads' => 'Đặc sắc',
    'Save' => 'Tiết kiệm',
    'All Ads' => 'Tất cả Quảng cáo',
    'Sort by' => 'Sắp xếp theo',
    'Price : Low to High' => 'Price : Thấp đến cao',
    'Price : High to Low' => 'Price : Cao đến thấp',
    'Relevance' => 'Sự liên quan',
    'Date' => 'Ngày',
    'Around :distance :unit' => 'Xung quanh :distance :unit',
    'Around' => 'Xung quanh',
    'All jobs' => 'Tất cả các công việc',
	'View all jobs' => 'Xem tất cả các công việc',
    'Select your region' => 'Chọn vùng của bạn',
    'Popular cities in' => 'Các thành phố nổi tiếng trong',
    'All regions' => 'Tất cả các vùng',
    'All Cities' => 'Tất cả các thành phố',
	'in :distance :unit around :city' => 'in :distance :unit around :city',
    ':distance :unit around :city' => ':distance :unit around :city',
    'in :category' => 'in :category',
	'in' => 'in',
	'at' => 'at',
    'Save Search' => 'Lưu tìm kiếm',
    'Please log in to save the Ads.' => 'Vui lòng đăng nhập để lưu quảng cáo.',
    'Please log in to save your search.' => 'Vui lòng đăng nhập để lưu tìm kiếm.',
    'Search saved successfully !' => 'Đã lưu tìm kiếm thành công !',
    'Search deleted successfully !' => 'Đã xóa tìm kiếm!',
	'Save Job' => 'Lưu việc làm ',
	'Saved Job' => 'Việc làm đã lưu',
	'Email Job' => 'Email việc làm',
	'a' => 'a',
	'per' => 'theo',
	'Clear all' => 'xóa tất cả',
	'hour' => 'giờ',
	'hours' => 'nhiều giờ',
	'day' => 'ngày',
	'days' => 'nhiều ngày',
	'month' => 'tháng',
	'months' => 'nhiều tháng',
	'year' => 'năm',
	'years' => 'nhiều năm',
	'Date Posted' => 'Ngày báo cáo',
	'Employment Type' => 'Kiểu việc làm',
	'Salary Pay Range' => 'Phạm vi lương',
	'Salary Range' => 'Mức lương',
    'GO' => 'GO',
	'Specialisms' => 'Chuyên môn',
	'Jobs at' => 'Việc làm tại',
	'Send by Email' => 'Gửi bởi Email',
	'Your Email' => 'Email của bạn',
	'Recipient Email' => 'Email người nhận',
	'Send the Job' => 'Gửi việc làm',
	'Send' => 'Gửi',
	'Jobs Found' => 'Tìm việc',
	'Browse Jobs' => 'Duyệt công việc',
	'Add Resume' => 'Thêm hồ sơ',
	'Add your Resume' => 'Thêm hồ sơ của bạn',

    'The countries' => 'Những quốc gia',
    'Our websites abroad' => 'Trang web của chúng tôi ở nước ngoài',
    
    'My Account' => 'Tài khoản của tôi',
    'Terminate Account' => 'chấm dứt Tài khoản',
    
    'We do not like robots' => 'Chúng tôi không thích robot :(',
    
    'Sitemap :country' => 'Sitemap - :country',
    
    'We regret that we can not process your request at this time. Our engineers have been notified of this problem and will try to resolve it as soon as possible.' => 'Chúng tôi rất tiếc vì chúng tôi không thể xử lý yêu cầu của bạn tại thời điểm này. Các kỹ sư của chúng tôi đã được thông báo về vấn đề này và sẽ cố gắng giải quyết vấn đề này càng sớm càng tốt.',
    'Whoops, looks like something went wrong. Please try later.' => 'Rất tiếc, hình như có gì đó không đúng. Hãy thử lại sau.',
    'Whoops, looks like something went wrong.' => 'Rất tiếc, hình như có gì đó không đúng.',
    'Whoops !' => 'Rất tiếc !',
    
    'Joined' => 'Gia nhập',

    'Your session has expired. Please try again.' => 'Phiên bản của bạn đã hết hạn. Vui lòng thử lại.',
    'The session has expired after a longtime. Please try again.' => 'Phiên bản đã hết hạn sau một thời gian dài. Vui lòng thử lại.',
    'Page not found' => 'Trang không tìm thấy ',
    'Oops ! Error 404. Page not found.' => 'Rất tiếc! Lỗi 404 - Không tìm thấy trang.',
    'Meanwhile, you may <a href=":url">return to homepage</a>' => 'Trong khi đó, bạn có thể <a href=":url">Trở về trang chủ</a>',

    'views' => 'lượt xem',
    'View More' => 'Xem thêm',
    'View Less' => 'Xem ít hơn',
    'Free' => 'Miễn phí',
    
    
    'Step' => 'Bậc thang',
    'Informations about your Ad' => 'Thông tin về quảng cáo của bạn ',
    'Upload' => 'Tải lên',
    'Seller informations' => 'Thông tin người bán',
    'Select a package' => 'Chọn gói hàng',
    'Select a package and click "Finish"' => 'Chọn gói và nhấp vào "Finish"',
    'Next' => 'Kế tiếp',
    'Previous' => 'Trước',
    'Skip' => 'Bỏ qua',
    
    'Premium Ad' => 'Quảng cáo chất lượng cao',
    'The premium package help companies to promote their job ads by giving more visibility to their ads to attract more candidates and hire them faster.' => 'Gói ưu đãi giúp các công ty quảng bá quảng cáo việc làm của họ bằng cách tăng khả năng hiển thị quảng cáo của họ để thu hút nhiều ứng viên hơn và thuê nhanh hơn.',
    'Regular List' => 'Miễn phí',
    'Payment Method' => 'Phương thức thanh toán',
    'Payment Methods' => 'Phương thức thanh toán',
    'Payment Gateway' => 'Cổng thanh toán',
    'Payment Gateways' => 'Cổng thanh toán',
    'Gateway' => 'Gateway',
    'Gateways' => 'Gateways',
    'Finish' => 'Kết thúc',

    'Facebook Fans' => 'Người hâm mộ trên Facebook',
    'User' => 'Người dùng',
    'Users' => 'Người sử dụng',
	
    'View all Ads' => 'Xem tất cả Quảng cáo',
    'Browse by' => 'Duyệt bởi',
    'View more' => 'Xem thêm',
    
    'Error in sending mail. Please contact our engineers: :app_email' => 'Lỗi khi gửi thư. Vui lòng liên hệ với các kỹ sư của chúng tôi: :app_email',
    'The sending messages is not enabled. Please check the SMTP settings in the /.env file.' => 'Các tin nhắn gửi không được kích hoạt. Vui lòng kiểm tra cài đặt SMTP trong thư mục <code>/.env</code>.',
    'The sending messages is not enabled. Please check the SMTP settings in the admin.' => 'Các tin nhắn gửi không được kích hoạt. Vui lòng kiểm tra cài đặt SMTP trong quản trị viên.',
    
    'Your account has been deleted.' => 'Tài khoản của bạn đã bị xóa.',
    'Your account has been deleted. We regret you.' => 'Tài khoản của bạn đã bị xóa. Chúng tôi rất tiếc bạn.',
    'Your account has been deleted. We regret you. <a href=":url">Re-register</a> if that is a mistake.' => 'Tài khoản của bạn đã bị xóa. Chúng tôi rất tiếc bạn. <a href=":url"> Đăng ký lại </a> nếu đó là lỗi.',

    'We have received your payment.' => 'Chúng tôi đã nhận được thanh toán của bạn.',
    'We have received your payment. Please check your inbox to activate your ad.' => 'Chúng tôi đã nhận được thanh toán của bạn. Vui lòng kiểm tra hộp thư đến của bạn để kích hoạt quảng cáo của bạn.',
    'We have not received your payment. Payment cancelled.' => 'Chúng tôi chưa nhận được thanh toán của bạn. Thanh toán bị hủy.',
    'We have not received your payment. An error occurred.' => 'Chúng tôi chưa nhận được thanh toán của bạn. Đã xảy ra lỗi.',

    'Address' => 'Địa chỉ',
    'Fill an address to display on Google Maps.' => 'Điền địa chỉ để hiển thị trên Google Maps.',
    
    'Unknown error. Please try again in a few minutes.' => 'Lỗi không rõ. Vui lòng thử lại trong vài phút.',
    'Email address not found. You can\'t use your :provider account on our website.' => 'Không tìm thấy địa chỉ email. Bạn không thể sử dụng tài khoản của bạn :provider trên trang web của chúng tôi.',

    'Payable Amount' => 'Số tiền phải trả',

	'Home - Latest Jobs' => '<span style="font-weight: bold;">Việc làm</span> muộn nhất',
	'Home - Featured Jobs' => ' <span style="font-weight: bold;">Việc làm</span> đặc sắc',
	'Similar Jobs' => 'Similar <span style="font-weight: bold;">Việc làm</span> giống',
	'More jobs at :distance :unit around :city' => 'Thêm việc làm tại :distance :unit xung quanh <span style="font-weight: bold;">:city</span>',
	'Home - Featured Companies' => ' <span style="font-weight: bold;">Công ty</span> đặc biệt',

	'Error' => 'Lỗi',
	'Unknown error' => 'Lỗi không rõ',
	'Error. Please select another category.' => 'Lỗi. Vui lòng chọn một danh mục khác.',
	'Error. Please select another location.' => 'Lỗi. Vui lòng chọn một vị trí khác.',
	'Error. Post doesn\'t exists.' => 'Lỗi. Bài đăng không tồn tại.',

	'Unactivated ads' => 'Công việc không được biết đến',
	'Activated ads' => 'Công việc kích hoạt',
	'User Registrations' => 'Đăng ký Người dùng',
	'Activated countries' => 'Các quốc gia đã cài đặt ',

	'Connect with Facebook' => 'Kết nối với <strong>Facebook</strong>',
	'Connect with Google' => 'Kết nối với <strong>Google</strong>',
	'Connect with Twitter' => 'Kết nối với <strong>Twitter</strong>',
	'or' => 'or',

    'Premium ad' => 'Premium ad',
    'Not available' => 'Không có sẵn',
    'Upgrade' => 'Nâng cấp',
    'Current' => 'Hiện hành',

    'Help' => 'Help',
    'To launch your website for several countries you need to activate these countries.' => 'Để khởi chạy trang web của bạn cho một số quốc gia bạn cần kích hoạt các quốc gia này.',
    'By disabling or removing a country the ads of this country (also) will be deleted.' => 'Bằng cách vô hiệu hoặc xóa một quốc gia, các quảng cáo của quốc gia này (cũng) sẽ bị xóa.',

    'Contact' => 'Liên hệ chúng tôi',
    'Contact us' => 'Liên hệ chúng tôi',
    'Contact Us' => 'Liên hệ chúng tôi',
    'Login Area' => 'Khu vực Đăng nhập',
    'Knowledge Base' => 'Kiến thức cơ bản',
    'Subject' => 'Môn học',
    'Anti-scam' => 'Anti-scam',

    'Featured' => 'Đặc sắc',
    'Expired' => 'Đã hết hạn',

    'Payment Details' => 'Chi tiết thanh toán',

    /* ===== v2.0 ===== */
    'Username' => 'Tên đăng nhập',
    'Email or Phone' => 'Email or Phone',
	'Email address' => 'Email address',
    'SMS Code' => 'SMS Code',
    'Token' => 'Token',
    'Code' => 'mã kích hoạt',
    'Code received by Email' => 'Mã nhận được qua Email',
    'Code received by SMS' => 'Mã nhận được qua SMS',
    'Code received by SMS or Email' => 'Mã nhận được qua SMS hoặc Email',
    'Validation Code' => 'Mã xác nhận',
    'Enter the validation code' => 'Nhập mã xác nhận',
    'Enter the code you received by Email in the field below' => 'Nhập mã bạn nhận được qua Email trong trường bên dưới',
    'Enter the code you received by SMS in the field below' => 'Nhập mã bạn nhận được qua SMS trong trường bên dưới',
    'Enter the code you received by SMS or Email in the field below' => 'Nhập mã bạn nhận được qua SMS hoặc Email trong trường bên dưới',
    'The entered code is invalid.' => 'Mã đã nhập không hợp lệ.',
    'These credentials do not match our records.' => 'Những chứng chỉ này không khớp với hồ sơ của chúng tôi.',
	'The code does not match  your email or phone number.' => 'Mã không khớp với số điện thoại hoặc email của bạn.',
	'The code does not match  your email.' => 'Mã không khớp với email của bạn.',
    'The code does not match  your phone number.' => 'Mã không khớp với số điện thoại của bạn.',
    'The entered value is not registered with us.' => 'Giá trị đã nhập không được đăng ký với chúng tôi.',
    'This feature has been turned off in demo mode.' => 'Tính năng này đã bị tắt trong chế độ demo.',
    'Photo' => 'Ảnh',
    'Option' => 'Tùy chọn',
    'Back' => 'Quay lại',
    'Back to the Item' => 'Trở lại mục',
    'Report for :title' => 'Báo cáo cho ":title"',
    'Send a report for :title' => 'Gửi báo cáo cho ":title"',
    'Home - Sponsored Jobs' => 'Tài trợ <span style="font-weight: bold;">Công việc</span>',
    'Photos' => 'Photos',
    'Images' => 'Images',
    'Preview' => 'Preview',
    'Done' => 'Done',
    'The pictures have been updated' => 'Các hình ảnh đã được cập nhật',
    'Are you sure you want to delete this picture?' => 'Bạn có chắc chắn muốn xóa ảnh này?',
    'The picture has been deleted.' => 'Ảnh đã bị xóa.',
    'Post not found' => 'Không tìm thấy bài đăng',
    'Upload Status' => 'Trạng thái tải lên',
    'The picture #:key is required.' => 'Hình ảnh #:key bắt buộc.',
    'The picture #:key must be image.' => 'Hình ảnh #:key  phải là hình ảnh.',
    'The picture #:key may not be greater than :max.' => 'Hình ảnh #:key không được lớn hơn :max.',
    'Uploaded file #index successfully' => "'<li>' + 'Uploaded file # ' + (index + 1) + ' - '  + fname + ' successfully.' + '</li>'",
    'Uploaded file #key successfully' => "'<li>' + 'Uploaded file # ' + (key + 1) + ' - '  + fname + ' successfully.' + '</li>'",
    'Do you want add more pictures?' => 'Bạn có muốn thêm hình ảnh khác không??',
    'Add more pictures?' => 'Thêm hình ảnh khác?',
    'Upload pictures' => 'Tải ảnh lên',
    'Upload the picture' => 'Tải lên hình ảnh',
    'Upload files' => 'Tải tệp lên',
    'Upload the file' => 'Tải tệp lên',
    'Send' => 'Gửi',
    'Pay' => 'Trả',
    'Pricing' => 'Giá',
    'Packages' => 'Gói',
    'Package' => 'Trọn gói',
    'The type of admin does not exist.' => 'Quản trị viên không tồn tại.',
    'No admin. division doesn\'t exists for the current country.' => 'Không có quản trị viên. sự phân chia không tồn tại đối với quốc gia hiện tại '.,
    'area:' => 'area:',
    'Enter a city name OR a state name with the prefix ":prefix" like: :prefix' => 'Nhập tên thành phố hoặc tên tiểu bang có tiền tố ":prefix" like: :prefix',
    'State Name' => 'Tên nhà nước',
    'for' => 'for',
    'among' => 'trong số',
    'inside' => 'phía trong',
    'within' => 'bên trong',
    'of' => 'of',
    'from' => 'from',
    'Post saved in favorites successfully !' => 'Bài đăng đã lưu trong mục yêu thích đã thành công!',
    'Post deleted from favorites successfully !' => 'Bài đăng đã xoá khỏi mục yêu thích đã thành công !',
    'An activation link has been sent to you to verify your email address.' => 'Một liên kết kích hoạt đã được gửi đến bạn để xác minh địa chỉ email của bạn.',
    'An activation code has been sent to you to verify your phone number.' => 'Mã kích hoạt đã được gửi cho bạn để xác minh số điện thoại của bạn.',
    'The activation link has been sent to you to verify your email address.' => 'Liên kết kích hoạt đã được gửi tới bạn để xác minh địa chỉ email của bạn.',
    'The activation code has been sent to you to verify your phone number.' => 'Mã kích hoạt đã được gửi cho bạn để xác minh số điện thoại của bạn.',
    'Resend the verification message to verify your email address.' => 'Gửi lại thông báo xác minh để xác minh địa chỉ email của bạn.',
    'Resend the verification message to verify your phone number.' => 'Gửi lại thông báo xác minh để xác minh số điện thoại của bạn.',
    'Re-send' => 'gửi lại',
    'Entity ID not found.' => 'không tìm thấy ID.',
    'Congratulation :name ! Your :field has been verified.' => 'Chúc mừng :name ! :field của bạn đã được xác minh.',
    'Your :field is already verified.' => ':field của bạn đã được xác minh.',
    'Your :field verification has failed.' => ':field của bạn xác minh đã thất bại.',
	'Homepage' => 'Trang chủ',
	'Messages' => 'Tin nhắn',
	'Messages Received' => 'Nhận Tin nhắn',
	'Messages Received on :app_name' => 'Nhận tin nhắn trong :app_name',
	'Ad' => 'Ad',
	'Download' => 'Tải về',
	'View' => 'Xem',
	'Transactions' => 'Giao dịch ',
	'Transaction' => 'Giao dịch ',
	'My Transactions' => 'Giao dịch của tôi',
	'My Transactions on :app_name' => 'Giao dịch của tôi trong :app_name',
	'Description' => 'Miêu tả',
	'Value' => 'giá trị',
	'Status' => 'Trạng thái',
	'Pending payment' => 'Trong khi chờ thanh toán',
	'Pending' => 'Đang chờ xử lý',
	'Paid by' => 'Trả bởi',
	'1 :entity has been deleted successfully.' => '1 :entity đã bị xóa thành công.',
	'x :entities has been deleted successfully.' => ':count :entities đã bị xóa thành công.',
	'messages' => 'Tin nhắn',
	'message' => 'thông điệp',
	'ad' => 'ad',
    'ads' => 'Quảng cáo',
	'post' => 'ad',
    'posts' => 'ads',
	'Message for' => 'Message for',
	'Reply' => 'Reply',
	'Sender\'s Name' => 'Tên người gửi',
	'Sender\'s Email' => 'Email người gửi',
	'Sender\'s Phone' => 'Phone người gửi',
	'You have already answered this message.' => 'Bạn đã trả lời thư này.',
    'Error on user\'s login.' => 'Lỗi đăng nhập của người dùng.',
    'The activation link has been sent to the user to verify his email address.' => 'Liên kết kích hoạt đã được gửi tới người dùng để xác minh địa chỉ email của anh ta.',
    'The activation code has been sent to the user to verify his phone number.' => 'Mã kích hoạt đã được gửi đến người dùng để xác minh số điện thoại của bạn.',
    'The :field is required.' => ':field là bắt buộc.',
    'The :field is required. And cannot be 0.' => ':field là bắt buộc. Và không thể là 0.',
    'The file of :field must be in the good format.' => 'Tập tin của :field phải ở định dạng tốt.',
    'The file of :field may not be greater than :max.' => 'Tập tin của :field không được lớn hơn :max.',
    'Additional Details' => 'Additional Details',
    'Map' => 'Map',
    'Maps' => 'Maps',
    'Location\'s Map' => 'Vị trí của bản đồ',
    'Specification' => 'Thông số kỹ thuật',
    'More Specification' => 'Thông số kỹ thuật khác',
    'Clear all the :category\'s filters' => 'Xóa tất cả :category của bộ lọc',
    'Are you sure you want to perform this action?' => 'Bạn có chắc chắn muốn thực hiện hành động này không?',
    'km' => 'km',
    'kilometer' => 'kilometer',
    'kilometers' => 'kilometers',
    'count_km' => '{0} km|{1} km|[2,*] km',
    'count_kilometers' => '{0} kilometer|{1} kilometer|[2,*] kilometers',
    'mi' => 'mi',
    'mile' => 'mile',
    'miles' => 'miles',
    'count_mi' => '{0} mi|{1} mi|[2,*] mi',
    'count_miles' => '{0} mile|{1} mile|[2,*] miles',
	'Your reply has been sent. Thank you!' => 'Phản hồi của bạn đã được gửi. Cảm ơn bạn!',
	':number characters maximum' => ':number tối đa ký tự',
	'Fax' => 'Fax',
	'Ad\'s Details' => 'Ad\'s Details',
	'Job\'s Details' => 'Job\'s Details',
	'Select a Company' => 'Select a Company',
	'New Company' => 'New Company',
	'Please select a company or \'New Company\' to create one.' => 'Vui lòng chọn một công ty hoặc \'công ty mới\' để tạo một công ty.',
	'Companies List' => 'Danh sách công ty',
	'My companies' => 'Công ty của tôi',
	'My Companies List' => 'Danh sách công ty của tôi',
	'My Companies List - :app_name' => 'Danh sách công ty của tôi - :app_name',
	'Create a new company' => 'Tạo một công ty mới',
	'Create a new company - :app_name' => 'Tạo một công ty mới - :app_name',
	'Edit the Company' => 'Chỉnh sửa Công ty',
	'Edit the Company - :app_name' => 'Chỉnh sửa Công ty - :app_name',
	'companies' => 'Các công ty',
	'company' => 'Công ty',
	'Companies' => 'Các công ty',
	'Your company has created successfully.' => 'Công ty của bạn đã tạo thành công.',
	'Your company details has updated successfully.' => 'Chi tiết công ty của bạn đã được cập nhật thành công.',
	'Select a Resume' => 'Chọn một Hồ Sơ',
	'New Resume' => 'Hồ sơ mới',
	'Please select a resume or \'New Resume\' to add one.' => 'Vui lòng chọn một sơ yếu lý lịch hoặc \'hồ sơ mới\' để thêm một hồ sơ.',
	'Resumes List' => 'Danh sách ứng viên',
	'My resumes' => 'Hồ sơ của tôi',
	'My Resumes List' => 'Danh sách hồ sơ của tôi',
	'My Resumes List - :app_name' => 'Danh sách hồ sơ của tôi - :app_name',
	'Add a new resume' => 'Thêm một sơ yếu lý lịch mới',
	'Create a resume' => 'Tạo một sơ yếu lý lịch ',
	'Create a resume - :app_name' => 'Tạo một sơ yếu lý lịch - :app_name',
	'Edit the resume' => 'Chỉnh sửa hồ sơ',
	'Edit the resume - :app_name' => 'Chỉnh sửa hồ sơ - :app_name',
	'resumes' => 'hồ sơ',
	'resume' => 'tiếp tục',
	'Your resume has created successfully.' => 'Sơ yếu lý lịch của bạn đã tạo thành công.',
	'Your resume has updated successfully.' => 'Hồ sơ của bạn đã được cập nhật thành công.',
	'File' => 'Tập tin',
	'Files' => 'Các tập tin',
	'Resume File' => 'Tiếp tục Tệp tin',
	'prev' => 'lùi',
	'next' => 'kế tiếp',
	'Application URL' => 'URL ứng dụng',
	'Candidates will follow this URL address to apply for the job.' => 'Ứng viên sẽ làm theo địa chỉ URL này để áp dụng cho công việc.',
	'Tags' => 'Thẻ',
	'Tag' => 'Nhãn',
	'Enter the tags separated by commas.' => 'Nhập các thẻ được phân cách bằng dấu phẩy.',
	'add a tag' => 'thêm một đánh dấu',
	'Click to see' => 'Bấm để xem',
	'No jobs were found for this company.' => 'Không tìm thấy công việc cho công ty này',
	'Contact Information' => 'Thông tin liên lạc',
	'Mobile Phone' => 'Điện thoại di động',
	'Payment pending' => 'Đang chờ thanh toán',
	'Error found' => 'Tìm thấy lỗi',
	'Contact & Sitemap' => 'Liên hệ & Sơ đồ trang web',
	'Mobile Apps' => 'Mobile Apps',
	'iOS app' => 'iOS app',
	'Android App' => 'Android App',
	'Available on the App Store' => 'Có sẵn trên App Store',
	'Available on Google Play' => 'Có sẵn trên Google Play',
	'Follow us on' => 'Theo dõi chúng tôi tại',
	'Powered by' => 'Được hỗ trợ bởi',
	'Select your Country' => 'Chọn quốc gia của bạn',
	'Select a Country' => 'Chọn một quốc gia',
	'See you soon.' => 'hẹn sớm gặp lại.',
	'on' => 'on',
	'Duration' => 'Thời lượng',
	'Loading' => 'Tải',
	'Processing' => 'cải biến',
	'Your picture has been reorder successfully' => 'Hình ảnh của bạn đã được sắp xếp lại thành công',
	'Add Listing' => 'Thêm danh sách',
	'Choose a city or region' => 'Chọn thành phố hoặc vùng',
	'Choose a state or region' => 'Chọn tiểu bang hoặc khu vực',
	'Conversations' => 'Cuộc trò chuyện',
	'Conversation' => 'Cuộc hội thoại',
	'Conversations Received' => 'Cuộc trò chuyện đã nhận ',
	'Conversations Received on :app_name' => 'Cuộc trò chuyện đã được :app_name',
	'Conversations Started' => 'Cuộc trò chuyện bắt đầu ',
	'Conversations Started on :app_name' => 'Cuộc trò chuyện bắt đầu :app_name',
	'Received at' => 'Nhận tại',
	'Related to the ad' => 'Liên quan đến quảng cáo ',
	'Sender' => 'gửi đi',
	'Click here to read the messages' => 'Nhấp vào đây để đọc các tin nhắn',
	'Click here to see' => 'Nhấp vào đây để xem',
	'Reply to' => 'Trả lời',
	'Started by' => 'Bắt đầu bởi',
	'Created by' => 'Được tạo bởi',
	':number max' => ' Tối đa :number',
	'Impersonate this user' => 'Mạo danh người dùng này ',
	'Leave impersonation' => 'Để lại mạo danh',
	'Leave' => 'Rời khỏi',
	'The current user can\'t impersonate' => 'Người dùng hiện tại không thể mạo danh',
	'The destination user can\'t be impersonated' => 'Người dùng đích không thể bị giả mạo',
	'Can\'t be accessed by an impersonator' => 'Không thể được truy cập bởi một người giả mạo',
	'Cannot impersonate yourself' => 'Không thể mạo nhận mình ',
	'Cannot impersonate admin users' => 'Không thể mạo danh người dùng quản trị ',
	'Cannot impersonate unactivated users' => 'Không thể mạo danh người dùng bị vô hiệu hóa',
	'Admin users can\'t be deleted by this way.' => 'Người dùng quản trị không thể bị xóa theo cách này.',
	'Filters' => 'Bộ lọc',
	'This user no longer exists.' => 'Người dùng này không còn tồn tại.',
	'Maybe the user\'s account has been disabled or deleted.' => 'Có thể tài khoản của người dùng đã bị vô hiệu hoặc bị xóa.',
	'The results could not be loaded.' => 'Kết quả không thể được nạp.',
	'Please delete #t character' => "'Xin vui lòng xóa ' + t + ' nhân vật'",
	'Please enter #t or more characters' => "'Vui lòng nhập ' + t + '  hoặc nhiều ký tự'",
	'Loading more results…' => 'Tải thêm kết quả…',
	'You can only select #max item' => "'Bạn chỉ có thể chọn ' + e.maximum + ' item'",
	'No results found' => 'không có kết quả nào được tìm thấy',
	'Searching…' => 'Đang tìm kiếm…',






];
